### ISSUE TITLE
bug: maxAttempts firing all attempts, regardless

### ISSUE THREAD

**Issue by podrivo** [gamedig/node-gamedig#451] opened 2024-01-05 13:10 UTC
**Describe the bug**
I'm testing some querying for DayZ servers and sometimes it can take a little longer to get a response, or sometimes the response is not complete, etc, and this is normal, just like DayZ and mods work. So too avoid having to manually retry, I've set the `maxAttempts: 5` and notice that it will fire all 5 attempts, regardless. I've updated to `maxAttempts: 20` and it took forever, and it went through all 20. If I set to `maxAttempts: 1` and the server response is good, it will work on the first try, but adding `maxAttempts` will just increase time.

Feels like it's a bug, where it will repeat all attempts, but only the last one will successfully fire.

**Steps To Reproduce**
I'm testing this via JS in a Express app, using this code:

```js
let state = await gamedig.query({
    type: 'dayz',
    host: server.ip,
    port: server.port_query,
    requestRules: true,
    maxAttempts: 5,
    debug: true
})
```

**Expected behavior**
If I'm adding `maxAttempts: 20`, I was expecting to get a successful response maybe on the 3rd call or maybe the 7th, but it goes through all 20, every time.

I'm not sure this is related to DayZ, because I've only tested with this game. Also, not sure if this a feature or a bug.

Thank you! 🙏

**Comment by CosminPerRam** [comment] 2024-01-10 23:18
I couldn't reproduce this issue, could you provide some servers that you've tested and also attach with a query with debug?

**Comment by podrivo** [comment] 2024-01-10 23:58
Of course! Sorry I didn't provide those.
I've tested with this code, running on VS Code and macOS:

`node bin/gamedig --type dayz --requestRules --debug --maxAttempts 10 135.148.36.26:2403`

I've attached txt files with logs for max attempts 1, 5 and 10. You can test in whatever dayz server, because I haven't notice any difference. It will always throw success on the last attempt.

DayZ servers: `193.25.252.82:27016`, `189.127.165.117:2305`, `135.148.36.26:2403`.
More options: https://www.battlemetrics.com/servers/dayz

[log-1.txt](https://github.com/gamedig/node-gamedig/files/13895631/log-1.txt)
[log-5.txt](https://github.com/gamedig/node-gamedig/files/13895632/log-5.txt)
[log-10.txt](https://github.com/gamedig/node-gamedig/files/13895633/log-10.txt)

**Comment by CosminPerRam** [comment] 2024-01-11 00:45
The query runner has an attempt array which goes through your given port and if the game has a port offset it also adds that to the list, but the order it attempts its reversed compared to the order I've explained, in addition, it tries X attempts on all possible ports, so, for example:

Querying 193.25.252.82:27016 with `--maxAttempts 2` goes:
(Because `dayz` has `port_query_offset: 24714` in options):
1. Try 193.25.252.82:51730
2. Try 193.25.252.82:51730
(And now the next port in the attempt ports list is the user given one)
1. Try 193.25.252.82:27016... and success!

This could be avoided by adding `--givenPortOnly` but this is not really intended behaviour, it should first try the user given port and only if that fails the other ones, this is a one-liner fix and will link a PR shortly, thanks for catching this!

**Comment by podrivo** [comment] 2024-01-11 11:09
Hmm, interesting! So it is indeed something from DayZ world. It makes sense to me to change orders and only test the default port if a specific one is not provided.

Glad I could weight on this and start a conversation! I'll start using the `--givenPortOnly` on my calls from now on.

**Comment by CosminPerRam** [comment] 2024-01-16 23:25
Closing this as it's solved by using `--givenPortOnly`.

**Closed by CosminPerRam** 2024-01-16 23:25 UTC
Labels: bug
