### ISSUE TITLE
Minecraft - Ping is always 0

### ISSUE THREAD

**Issue by Emiliaaah** [gamedig/node-gamedig#233] opened 2021-06-15 08:23 UTC
When using the type minecraft it always returns 0.
But raw.vanilla.ping (in my case) does return the ping and not 0.

**Comment by mmorrisontx** [comment] 2021-06-15 23:28
Thanks for the report, definitely a bug.

**Comment by AlexandreSama** [comment] 2021-08-11 19:52
The bug is still there, but this is really weird ! I give you a screenshot about results

![Capture d’écran 2021-08-11 215136](https://user-images.githubusercontent.com/56075082/129094019-5c0e8a8d-6251-4e4d-a013-dc5ab292e1f2.png)

**Comment by mmorrisontx** [comment] 2021-08-11 23:35
For now, you can pull it from one of the raw subquery objects, unless someone wants to contribute a MR for pulling it into the merged response :)

**Closed** 2022-02-06 01:38 UTC

**Comment by WhyKickAmooCow** [comment] 2023-01-08 08:00
It looks like there may have been a regression, this still seems to be affecting me on version 4.0.5. Exactly the same symptoms in the return value, raw.vanilla.ping is still accurate but ping is always 0.
