### ISSUE TITLE
Add SCP: Secret Laboratory support.

### ISSUE THREAD

**Issue by ghost** [gamedig/node-gamedig#338] opened 2023-06-10 15:26 UTC
EDIT: Description restored

Hi, could you add a game like, SCP: Secret Lab (https://store.steampowered.com/app/700330/SCP_Secret_Laboratory/)
Thanks for the awesome project,
Reyah9999

**Comment by CosminPerRam** [comment] 2023-10-05 21:40
Related https://linuxgsm.com/servers/scpslserver/

**Comment by CosminPerRam** [comment] 2023-11-05 21:30
Hey, why did you closed, and pretty much tried to erase (edit the title and delete the initial description) this issue?
I have prioritized other stuff after seeing [this](https://steamcommunity.com/app/700330/discussions/0/1697167355229575012/), but I tried to create a server locally and there seem to be a query port, for what exactly I don't know for now but I will dig into it this week.

**Comment by CosminPerRam** [comment] 2023-11-05 21:54
I've made a quick nodejs script to run some generic protocols and it seemed it responded on the `minecraftvanilla` protocol haha.
![image](https://github.com/gamedig/node-gamedig/assets/7972857/6dc23bef-7c32-49a0-8820-799c7cbfda4c)
I think this pretty much means that they use a proprietary protocol, might take a while to add...

**Comment by podrivo** [comment] 2024-01-16 12:28
@CosminPerRam Are you running the [attempt_protocols.js](https://github.com/gamedig/node-gamedig/blob/master/tools/attempt_protocols.js) file to test this?

If so, should we add the other protocols to it?
https://github.com/gamedig/node-gamedig/blob/58c9c2cdade12f36c4df8eac08dedb33e7601378/protocols/index.js#L55-L61

**Comment by CosminPerRam** [comment] 2024-01-16 16:18
Yes, the tool would also benefit from some parallelization.

**Comment by podrivo** [comment] 2024-01-18 15:05
I got this IP `200.9.155.49:7777` from this server list: https://scplist.kr/ and ran `tools/attempt_protocols.js` but didn't got a response from any protocol. Used with port 7777, 7778 and also without a port.

**Comment by CosminPerRam** [comment] 2024-01-18 23:00
Made a steam discussions page a while back regarding this: [here](https://steamcommunity.com/app/700330/discussions/1/3823046931412543645/).
I've just sent an email to them, will update if they'll respond.

**Comment by podrivo** [comment] 2024-01-18 23:12
Nice! They mentioned an API to fetch server info, but you need to authenticate to get the server ID and your token:
https://support.scpslgame.com/article/61

**Comment by CosminPerRam** [comment] 2024-02-24 19:32
This is a duplicate of #197.

**Closed by CosminPerRam** 2024-02-24 19:32 UTC
Labels: enhancement, protocol
